// Code generated by mockery 2.7.4. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}
