// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	kava "github.com/kava-labs/rosetta-kava/kava"
	mock "github.com/stretchr/testify/mock"

	tenderminttypes "github.com/tendermint/tendermint/types"

	types "github.com/cosmos/cosmos-sdk/types"
)

// BalanceServiceFactory is an autogenerated mock type for the BalanceServiceFactory type
type BalanceServiceFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: addr, blockHeader
func (_m *BalanceServiceFactory) Execute(addr types.AccAddress, blockHeader *tenderminttypes.Header) (kava.AccountBalanceService, error) {
	ret := _m.Called(addr, blockHeader)

	var r0 kava.AccountBalanceService
	if rf, ok := ret.Get(0).(func(types.AccAddress, *tenderminttypes.Header) kava.AccountBalanceService); ok {
		r0 = rf(addr, blockHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kava.AccountBalanceService)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.AccAddress, *tenderminttypes.Header) error); ok {
		r1 = rf(addr, blockHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
