// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewBalanceServiceFactoryT is an autogenerated mock type for the NewBalanceServiceFactoryT type
type NewBalanceServiceFactoryT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewBalanceServiceFactoryT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewBalanceServiceFactoryT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewBalanceServiceFactoryT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewBalanceServiceFactoryT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewNewBalanceServiceFactoryT creates a new instance of NewBalanceServiceFactoryT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewBalanceServiceFactoryT(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewBalanceServiceFactoryT {
	mock := &NewBalanceServiceFactoryT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
