// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewAccountBalanceServiceT is an autogenerated mock type for the NewAccountBalanceServiceT type
type NewAccountBalanceServiceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewAccountBalanceServiceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewAccountBalanceServiceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewAccountBalanceServiceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewAccountBalanceServiceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewNewAccountBalanceServiceT creates a new instance of NewAccountBalanceServiceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewAccountBalanceServiceT(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewAccountBalanceServiceT {
	mock := &NewAccountBalanceServiceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
