name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Cache Go Modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      run: go install golang.org/x/lint/golint@latest && make lint

    - name: Build
      run: make build

    - name: Vet
      run: make vet

    - name: Test Unit
      run: make test

    - name: Test Integration
      run: KAVA_RPC_URL=http://50.16.212.18:26657 NETWORK=kava-mainnet PORT=4000 make test-integration

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 3m0s

  check-data-setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.setup_work.outputs.matrix}}
      workload: ${{steps.set_blks_per_chunk.outputs.blks_per_chunk}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - id: setup_work 
      env:
          START_INDEX: 1
          BLKS_PER_CHUNK: 40000
      run: echo "::set-output name=matrix::$(./scripts/setup.sh)"
    - id: set_blks_per_chunk
      run: echo "::set-output name=blks_per_chunk::40000"

  check-data:
    runs-on: ubuntu-latest
    needs: check-data-setup
    strategy:
      matrix: 
        range: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - run: |
          echo ${{ matrix.range }}
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: run check:data on mainnet
      env:
        START_INDEX: ${{ matrix.range }}
        COUNT: ${{ needs.setup.outputs.workload }}
      run: ./scripts/cli.sh
